# Generated by Django 3.2.5 on 2021-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
